### PR TITLE
WIP: Start of fixing to get around chagnes to ECCC WQ site

### LINKED ISSUE #6: data retrieval functions not working due to changes in ec database structure
The following functions do not work - likely more but I haven't tested: 

- `wq_sites()`
- `wq_site_data()`
- `wq_basin_data()`
- `wq_params()`

I'm not sure if it is worth fixing the package, I will try to get a sense of the package use before looking into changes.

### PR DESCRIPTION
**Pull request by ateucher**
Fixes #6 (when complete)

### CODE REVIEW

**Comment by ateucher** [comment]
@KarHarker - here's a start!

**Comment by KarHarker** [comment]
phew, nice work! I will keep looking into the errors when I get a chance. Seems like some background data is loading okay but the main `wq_site_data()` is still not working right

**Comment by ateucher** [comment]
@KarHarker I think I've mostly got it, would love your eyes on it if you are able!

**Comment by KarHarker** [comment]
Hi Andy - just had a tour of the changes and it is working great! Thanks so much for doing this

**Comment by ateucher** [comment]
Great! Thanks very much! I'll merge now and bump the version

**Pull request merged**
